language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.6"

# Temporarily use xenial with with sudo to install Python 3.7. References:
# https://github.com/travis-ci/travis-ci/issues/9069
# https://github.com/travis-ci/travis-ci/issues/9815
matrix:
  include:
    - python: "3.7"
      dist: xenial
      sudo: required

# Command to run tests
script: py.test
